feat(plasma-b2c): Add `TextField` components
salute-developers/plasma-react-native pull request #7
Opened 2024-06-18 11:12 UTC by neretin-trike

2024-06-22 17:37 UTC, shuga2704 requested changes

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Checkbox/Checkbox.tsx
> +export const checkboxCore = <T extends CheckboxConfig>(config?: T, theme?: Theme) => (
Для чего тут дженерик?

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Checkbox/Checkbox.tsx
> +    const onlyDescription = Boolean(!label && description);
```suggestion
    const onlyDescription = !label && description;
```

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Checkbox/Checkbox.tsx
> +        <Pressable style={style.root} disabled={disabled} onPress={() => onValueChange?.(checked)} {...rest}>
вынесем в хендлер onPress?

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Progress/Progress.tsx
> +        [value, view, size, theme?.mode],
Как будто депсы не те

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Progress/utils/getLinearVectorPoints.ts
> +    const cos = Math.cos(radians);
пригодились таки нам в жизни синусы и косинусы))

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Switch/Switch.tsx
> +        onValueChange,
Не стал юзать onChange по тем же причинам, что и в вебе?

2024-06-22 17:37 UTC, shuga2704 commented on core/core-components/src/components/Switch/Switch.tsx
> +        onValueChange?.(checked);
мы же в хендлерах не юзаем тернарники?

2024-06-26 19:50 UTC, Yeti-or approved these changes

2024-06-26 19:50 UTC, Yeti-or commented on core/core-components/src/components/TextField/TextField.styles.ts
> +    if (!viewStyle || !sizeStyle || !theme) {
а почему так может быть ?

2024-06-26 19:50 UTC, Yeti-or commented on libraries/plasma-b2c/src/components/TextField/TextField.config.ts
> +                contentLabelInnerPaddingTop: 4,
ну вот для такого кажется нам нужны пересечения
или все еще нет ?

2024-07-18 17:01 UTC, neretin-trike commented on core/core-components/src/components/Button/Button.tsx
> +        text,
это из-за дизайна. Если пользователь просто прокидывает текст, то он будет отображаться согласно нашему макету, если же он прокидывает children, то предполагается, что ему нужно что-то сложнее, чем просто текст

2024-07-18 17:02 UTC, neretin-trike commented on core/core-components/src/components/Button/Button.tsx
> +        [view, size, disabled, stretching, pin, theme?.mode],
не, view и size используются при расчете viewStyle и sizeStyle, соотвественно когда меняется размер или вьюха, то надо пересчитать стиль

2024-07-18 17:41 UTC, neretin-trike commented on core/core-components/src/components/Progress/Progress.tsx
> +        [value, view, size, theme?.mode],
тут также есть связь с sizeStyle, но view не нужно, ты прав, пасиб

2024-07-18 17:42 UTC, neretin-trike commented on core/core-components/src/components/Progress/utils/getLinearVectorPoints.ts
> +    const cos = Math.cos(radians);
ну не скажу, что я прям сам это рассчитывал :D

2024-07-18 17:55 UTC, neretin-trike commented on core/core-components/src/components/Checkbox/Checkbox.types.ts
> +    onValueChange?: (value: boolean) => void;
там если отдавать наружу, то будет семантическое несоответствие объекта события (onPress) и названия самого колбэка - onValueChange. Поэтому давай пока не, если понадобится кому-нить - дадим

2024-07-18 18:00 UTC, neretin-trike commented on core/core-components/src/components/Checkbox/Checkbox.tsx
> +    const onlyDescription = Boolean(!label && description);
если уберу явное приведение, то  надо будет в параметрах метода getStyle переменную onlyDescription делать типом React.Node, что не очень (опять таки название с типом не будет сходиться)

2024-07-18 18:02 UTC, neretin-trike commented on core/core-components/src/components/Checkbox/Checkbox.tsx
> +export const checkboxCore = <T extends CheckboxConfig>(config?: T, theme?: Theme) => (
он нужен тут, как в других компонентах для того, штобы возвращать корректные типы пользователям, которые получают компонент собранный с конфигом. Т.е. за счёт этого дженерика вернётся тип с пропсами view='default' | 'secondary' | 'tertiary' (и т.д., всё, что описано в конфиге)

2024-07-18 18:21 UTC, neretin-trike commented on core/core-components/src/components/Switch/Switch.tsx
> +        onValueChange,
не совсем, просто это нативный компонент Switch имеет колбэк с таким же названием

2024-07-18 18:24 UTC, neretin-trike commented on core/core-components/src/components/Switch/Switch.tsx
> +    ]);
это из-за дизайна. Если пользователь просто прокидывает текст, то он будет отображаться согласно нашему макету, если же он прокидывает children, то предполагается, что ему нужно что-то сложнее, чем просто текст

2024-07-18 18:24 UTC, neretin-trike commented on core/core-components/src/components/Switch/Switch.tsx
> +    ]);
не, view и size используются при расчете viewStyle и sizeStyle, соотвественно когда меняется размер или вьюха, то надо пересчитать стиль

2024-07-18 18:25 UTC, neretin-trike commented on libraries/plasma-b2c/src/components/TextField/TextField.config.ts
> +                contentLabelInnerPaddingTop: 4,
в целом да, для такого бы могло подойти, но пока не сделали этот механизм

2024-07-18 18:33 UTC, neretin-trike commented on core/core-components/src/components/TextField/TextField.styles.ts
> +    if (!viewStyle || !sizeStyle || !theme) {
это просто typeGuard, а в целом такое может быть если использовать компонент без конфига, как в случае Spinner в Button'e

2024-07-18 18:35 UTC, neretin-trike commented on core/core-components/src/components/ThemeProvider/ThemeProvider.types.ts
> +}
там суть в том, что я нужные настройки шрифта вытаскиваю исходя из сочетаний свойств font-weight и font-style, поэтому в данном случае особо смысла нет так делать 🤔

2024-07-18 18:44 UTC, merged